// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfcJ2EYNRyaJu18T9ACMWkyXLVtmYhTQk',
    appId: '1:978040115074:web:1d0d36ff01fb4f8008099b',
    messagingSenderId: '978040115074',
    projectId: 'flutter-32fe3',
    authDomain: 'flutter-32fe3.firebaseapp.com',
    storageBucket: 'flutter-32fe3.firebasestorage.app',
    measurementId: 'G-623D8L12MY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQdwFpbK2ZBmTs-bg_O9Zc3hBNnuLM1-w',
    appId: '1:978040115074:android:90e6518fc62ef0c508099b',
    messagingSenderId: '978040115074',
    projectId: 'flutter-32fe3',
    storageBucket: 'flutter-32fe3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9ufAh7WNp6k-NKfY-IFLUAagho1Jq3rY',
    appId: '1:978040115074:ios:f08adeda15a645d708099b',
    messagingSenderId: '978040115074',
    projectId: 'flutter-32fe3',
    storageBucket: 'flutter-32fe3.firebasestorage.app',
    iosBundleId: 'com.example.test3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9ufAh7WNp6k-NKfY-IFLUAagho1Jq3rY',
    appId: '1:978040115074:ios:f08adeda15a645d708099b',
    messagingSenderId: '978040115074',
    projectId: 'flutter-32fe3',
    storageBucket: 'flutter-32fe3.firebasestorage.app',
    iosBundleId: 'com.example.test3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfcJ2EYNRyaJu18T9ACMWkyXLVtmYhTQk',
    appId: '1:978040115074:web:c80ff3220eb32ee108099b',
    messagingSenderId: '978040115074',
    projectId: 'flutter-32fe3',
    authDomain: 'flutter-32fe3.firebaseapp.com',
    storageBucket: 'flutter-32fe3.firebasestorage.app',
    measurementId: 'G-M9V8M3V4R4',
  );
}
